import * as vscode from 'vscode';
import { Octokit } from '@octokit/rest';
import * as fs from 'fs-extra';
import * as path from 'path';

export class GitHubService {
    private octokit: Octokit | null = null;

    constructor() {
        this.initializeOctokit();
    }

    private async initializeOctokit() {
        // Try to get GitHub token from VS Code settings or environment
        const config = vscode.workspace.getConfiguration('fullstackgenie');
        let token = config.get<string>('githubToken');

        if (!token) {
            token = process.env.GITHUB_TOKEN;
        }

        if (!token) {
            // Prompt user for token
            const inputToken = await vscode.window.showInputBox({
                prompt: 'Enter your GitHub Personal Access Token',
                password: true,
                placeHolder: 'ghp_...',
                ignoreFocusOut: true
            });

            if (inputToken) {
                token = inputToken;
                // Optionally save to settings
                const save = await vscode.window.showQuickPick(['Yes', 'No'], {
                    placeHolder: 'Save token to workspace settings?'
                });
                if (save === 'Yes') {
                    await config.update('githubToken', token, vscode.ConfigurationTarget.Global);
                }
            }
        }

        if (token) {
            this.octokit = new Octokit({ auth: token });
        }
    }

    async createRepo(projectName: string, localPath: string): Promise<void> {
        if (!this.octokit) {
            vscode.window.showWarningMessage('GitHub token not configured. Skipping repository creation.');
            return;
        }

        try {
            // Get authenticated user
            const { data: user } = await this.octokit.users.getAuthenticated();

            // Create repository
            const { data: repo } = await this.octokit.repos.createForAuthenticatedUser({
                name: projectName,
                description: `Full-stack project generated by Full Stack Genie 🧞`,
                private: false,
                auto_init: false
            });

            // Add remote to local git
            const terminal = vscode.window.createTerminal({
                name: 'GitHub Setup',
                cwd: localPath
            });

            terminal.sendText(`git remote add origin ${repo.clone_url}`);
            terminal.sendText(`git branch -M main`);
            terminal.sendText(`git push -u origin main`);

            // Show success message with link
            vscode.window.showInformationMessage(
                `Repository created successfully!`,
                'Open GitHub'
            ).then((action) => {
                if (action === 'Open GitHub') {
                    vscode.env.openExternal(vscode.Uri.parse(repo.html_url));
                }
            });

        } catch (error: any) {
            if (error.status === 422) {
                vscode.window.showErrorMessage(`Repository "${projectName}" already exists on GitHub.`);
            } else {
                vscode.window.showErrorMessage(`Failed to create GitHub repository: ${error.message}`);
            }
            throw error;
        }
    }

    async validateToken(): Promise<boolean> {
        if (!this.octokit) {
            return false;
        }

        try {
            await this.octokit.users.getAuthenticated();
            return true;
        } catch {
            return false;
        }
    }
}
